name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: asikurr/my-node-app:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 182.160.123.220
          username: ${{ secrets.VPS_USERNAME }}  
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull asikurr/my-node-app:latest
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker run -d --name my-node-app -p 4000:4000 asikurr/my-node-app:latest